name: CI_action

on:
  push:
    branches:
      - main
      - Development
  pull_request:
    branches:
      - main
      - Development

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: lab2/cise_ass1a_worksheet2-frontend/

      - name: Run the tests
        run: npm test
        working-directory: lab2/cise_ass1a_worksheet2-frontend/

      - name: Build
        run: npm run build
        working-directory: lab2/cise_ass1a_worksheet2-frontend/
